name: 'Manual Production Release'

on:
  workflow_dispatch:
    inputs:
        tag:
          description: "Tag"
          required: true
          type: string

jobs:
  release:
    name: Release private image to public ECR
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.UTILITY_ACCOUNT_ID }}:role/Digabi2PrivateEcrGithubActionsAccessRole
          aws-region: eu-north-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: Pull private image
        run: docker pull ${{ steps.login-ecr.outputs.registry }}/geogebra:${{ inputs.tag }}
      - name: Configure Public ECR AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.UTILITY_ACCOUNT_ID }}:role/Digabi2PublicEcrGithubActionsAccessRole
          aws-region: us-east-1
      - name: Login to Amazon ECR
        id: login-public-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public
      - name: Tag image
        run: docker tag ${{ steps.login-ecr.outputs.registry }}/geogebra:${{ inputs.tag }} ${{ steps.login-public-ecr.outputs.registry }}/u3p9b9p9/geogebra-public:${{ github.ref_name }}
      - name: Push image
        run: docker push ${{ steps.login-public-ecr.outputs.registry }}/u3p9b9p9/geogebra-public:${{ inputs.tag }}
